# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sirish Oruganti
author: sirishoruganti
email: sirishoruganti@utexas.edu
description: > # this means to ignore newlines until "baseurl:"
  The personal, academic webpage for Sirish Oruganti.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.sirishoruganti.com" # the base hostname & protocol for your site
repository: sirishoruganti/sirishoruganti.github.io
twitter_username: sirishoruganti
twitter:
  username: sirishoruganti
github_username:  sirishoruganti
scholar_username: sirishoruganti
orcid_username: 0000-0002-1065-605X
linkedin_username: sirishoruganti
google_site_verification: v47833PE1BNhMRvPyy3gqvFr_k9dfDy8fBGMboEV3eI
social:
  name: Sirish Oruganti
  links:
    - https://twitter.com/sirishoruganti/
    - https://www.linkedin.com/in/sirishoruganti/
    - https://github.com/sirishoruganti/
logo: /assets/images/UVic_logo.png

# Build settings
markdown: kramdown

navigation:
  - title: Home
    url: /
  - title: Biography
    url: /biography.html
  - title: Publications
    url: /publications.html
  - title: Contact
    url: /contact.html

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  